sudo: required
dist: trusty

addons:
  apt:
    source:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - '9.2'
  - '8.0'
  - '7.0'

before_script:
  - npm install -g @angular/cli

script:
  - cd web-app
  - npm install
  - npm run test
  - npm run build

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always
