sudo: required
dist: trusty

addons:
  apt:
    source:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - '9.2'
  - '8.0'

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - cd web-app
  - npm install
  - ng test --single-run --watch=false --code-coverage
  - npm run build

after_script:
  - cat ./web-app/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always
